In [2]:
from numpy import *
import numpy as np
numbers = np.array([-5, 4, 3, 0, 2, 1])
pos = numbers[numbers>0]
print(pos)

[4 3 2 1]


In [4]:

a = np.array([10,20,30])
b = np.array([30,40,50])
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[40 60 80]
[-20 -20 -20]
[0.33333333 0.5        0.6       ]
[ 300  800 1500]


In [11]:
a = np.array([[20, 30],[40, 50, 60]])

print(a)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [13]:
b = np.array([[20, 30, 50],[40, 50, 60]])
print(b)
print(type(b))

[[20 30 50]
 [40 50 60]]
<class 'numpy.ndarray'>


In [12]:
print("hello")

hello


In [14]:
b = np.array([[20, 30, 50],[40, 50, 60],[1, 2, 3]])
print(b)

[[20 30 50]
 [40 50 60]
 [ 1  2  3]]


In [16]:
b = np.array([20, 30, 50])
print(b[:2])

[20 30]


In [18]:
b = np.array([[20, 30, 50],[40, 50, 60],[1, 2, 3]])
print(b[:2,:2])

[[20 30]
 [40 50]]


In [22]:
b = np.array([[20, 30, 50],[40, 50, 60],[1, 2, 3]])
print(np.shape(b)) #rows, columns
print(np.size(b)) #num of elements
print(np.ndim(b)) #dimension of array
print(np.dtype) #datatype of array
print(len(b)) #length of array
print(b.astype(float)) #change the datatype

(3, 3)
9
2
<class 'numpy.dtype'>
3
[[20. 30. 50.]
 [40. 50. 60.]
 [ 1.  2.  3.]]


In [23]:
a = np.array([10,20,30])
b = np.array([30,40,50])

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[40 60 80]
[-20 -20 -20]
[ 300  800 1500]
[0.33333333 0.5        0.6       ]


In [24]:
a = np.array([10,20,30])
b = np.array([3])
print(np.power(a,b))

[ 1000  8000 27000]


In [26]:
a = np.array([1000, 8000, 27000])
print(np.cbrt(a))
print(a.astype(int))

[10. 20. 30.]
[ 1000  8000 27000]


In [33]:
#Concatnate
a = np.array([[10,20,30],[130,240,540]])
b = np.array([[1,2,3],[3,4,5]])

print(np.concatenate([a,b]))
print(np.hstack([a,b])) 
print(np.vstack([a,b]))

[[ 10  20  30]
 [130 240 540]
 [  1   2   3]
 [  3   4   5]]
[[ 10  20  30   1   2   3]
 [130 240 540   3   4   5]]
[[ 10  20  30]
 [130 240 540]
 [  1   2   3]
 [  3   4   5]]


In [34]:
a = np.array([10,20,30,130,240,540])
print(np.array_split(a,3))

[array([10, 20]), array([ 30, 130]), array([240, 540])]


In [35]:
a = np.array([[10,20,30],[130,240,540]])
print(np.array_split(a,3))

[array([[10, 20, 30]]), array([[130, 240, 540]]), array([], shape=(0, 3), dtype=int32)]


In [38]:
# addding and removing

a = np.array([10,20,30,130,240,540])
print(np.append(a,90))
print(np.insert(a,2,50))
print(np.delete(a,3))

[ 10  20  30 130 240 540  90]
[ 10  20  50  30 130 240 540]
[ 10  20  30 240 540]


In [41]:
#Sort, Filter, Search
a = np.array([[190,220,300,130,240,540],[6,3,5,2,5,1]])
print(np.sort(a))

[[130 190 220 240 300 540]
 [  1   2   3   5   5   6]]


In [42]:
a = np.array([10,20,30,130,240,540])
s = np.where(a == 240)
print(s)

(array([4], dtype=int64),)


In [43]:
a = np.array([10,20,30,130,240,540])
filter_array = a>100
new = a[filter_array]
print(new)

[130 240 540]


In [45]:
#Aggregation Functions
a = np.array([10,20,30,130,240,540])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

970
540
10
6
161.66666666666666
[ 10  30  60 190 430 970]
[         10         200        6000      780000   187200000 -1991215104]


In [49]:
#Statistical Functions
import statistics as stats
baked_food = [200, 300, 150, 130, 200,280, 170, 188]

a = np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))


202.25
194.0
200
55.68157235567257
3100.4375


In [52]:
tobacco_consumption = [30, 50, 10, 30,50, 40]
deaths = [100, 120 ,70, 100, 120 , 112]

print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]
